  name: test-and-build
  on:
    pull_request:
      types:
        - opened
      branches:
        - main
      paths-ignore:
        - '.github/**'
  jobs:
    tests:
      name: Unit tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v1
        - name: Set up JDK
          uses: actions/setup-java@v1
          with:
            java-version: '17'
        - name: Run Tests
          run: mvn test
