name: Test
env:
  ARTIFACT_NAME: 'devops-upskill'
on:
  push:
    branches: [main, develop]
jobs:
  build-jar:
    name: Build JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'
      - name: Get project's version
        run:  echo "PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ env.PROJECT_VERSION }}.jar
          path: target/${{ env.ARTIFACT_NAME }}-${{ env.PROJECT_VERSION }}.jar
      - name: Push JAR
        uses: advancedcsg-open/action-jfrog-cli@master
        with:
          url: 'https://ivailozd.jfrog.io/'
          credentials type: 'apikey'
          apikey: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
          args: u "${{ env.ARTIFACT_NAME }}-${{ env.PROJECT_VERSION }}.jar" "default-maven-local/" --recursive=false --build-name=${{ env.ARTIFACT_NAME }}-${{ env.PROJECT_VERSION }}.jar